/**
 * solarWindData.js
 *
 * Loads and queries historical solar wind data.
 *
 * Monthly JSON files are loaded lazily as the user navigates through time.
 * Data files: public/data/solarwind/YYYY-MM.json
 * Generated by: scripts/convert-solarwind.js
 *
 * Missing hours in the source are stored as null.  getSolarWindAtTime() linearly
 * interpolates across gaps up to MAX_INTERP_GAP hours.  Longer gaps return null
 * for that parameter.  The `interpolated` flag in the return value is true whenever
 * any parameter was filled by interpolation, so the UI can indicate this.
 */

// Cache: "YYYY-MM" → { year, month, epochs, vSw, nSw, By, Bz, Dst, G1, G2 }
const monthCache = new Map();

// Merged view of all loaded months, sorted by epoch. Rebuilt on each new load.
let mergedView = null;

// In-flight fetches — deduplicates concurrent requests for the same month.
const inFlight = new Map();

const MAX_INTERP_GAP = 6; // maximum gap length (hours) to interpolate across

// Callback fired whenever a new month is loaded and the merged view is rebuilt.
let _onMonthLoaded = null;

/** Register a callback invoked after each new month is successfully cached. */
export function setOnMonthLoaded(cb) { _onMonthLoaded = cb; }

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function monthKey(year, month) {
  return `${year}-${String(month).padStart(2, '0')}`;
}

function rebuildMergedView() {
  if (monthCache.size === 0) { mergedView = null; return; }

  // Sort all cached months chronologically by their first epoch.
  const sorted = [...monthCache.values()].sort((a, b) => a.epochs[0] - b.epochs[0]);

  const epochs = [], vSw = [], nSw = [], By = [], Bz = [], Dst = [], G1 = [], G2 = [];
  for (const d of sorted) {
    for (let i = 0; i < d.epochs.length; i++) {
      epochs.push(d.epochs[i]);
      vSw.push(d.vSw[i]);
      nSw.push(d.nSw[i]);
      By.push(d.By[i]);
      Bz.push(d.Bz[i]);
      Dst.push(d.Dst[i]);
      G1.push(d.G1 ? d.G1[i] : null);
      G2.push(d.G2 ? d.G2[i] : null);
    }
  }

  mergedView = { epochs, vSw, nSw, By, Bz, Dst, G1, G2 };
}

// Binary search — floor index.
// Returns the largest index i such that epochs[i] <= target.
function floorIndex(epochs, target) {
  let lo = 0, hi = epochs.length - 1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (epochs[mid] <= target) lo = mid;
    else hi = mid - 1;
  }
  return lo;
}

// Interpolate across null gaps.
// Searches left and right from idx for the nearest non-null neighbours.
function resolveNull(arr, idx) {
  let lo = idx - 1;
  while (lo >= 0 && arr[lo] === null) lo--;

  let hi = idx + 1;
  while (hi < arr.length && arr[hi] === null) hi++;

  const hasLo = lo >= 0;
  const hasHi = hi < arr.length;

  if (!hasLo && !hasHi) return { value: null, interpolated: false };
  if (!hasLo)           return { value: arr[hi], interpolated: true };
  if (!hasHi)           return { value: arr[lo], interpolated: true };

  const gapSize = hi - lo - 1;
  if (gapSize > MAX_INTERP_GAP) return { value: null, interpolated: false };

  const t = (idx - lo) / (hi - lo);
  return { value: arr[lo] + t * (arr[hi] - arr[lo]), interpolated: true };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Load one month's data file.
 *
 * Safe to call multiple times — fetches only once per month (deduplicates
 * concurrent requests; caches on success; silently ignores 404s).
 *
 * @param {number} year
 * @param {number} month  1–12
 * @returns {Promise<void>}
 */
export async function loadMonth(year, month) {
  const key = monthKey(year, month);
  if (monthCache.has(key)) return;
  if (inFlight.has(key)) return inFlight.get(key);

  const mm = String(month).padStart(2, '0');
  const promise = (async () => {
    try {
      const response = await fetch(`./data/solarwind/${year}-${mm}.json`);
      if (!response.ok) return; // silently skip missing months (404, etc.)
      const data = await response.json();
      monthCache.set(key, data);
      rebuildMergedView();
      if (_onMonthLoaded) _onMonthLoaded();
    } finally {
      inFlight.delete(key);
    }
  })();

  inFlight.set(key, promise);
  return promise;
}

/**
 * Ensure the month containing unixSec is loaded, plus its immediate neighbors.
 *
 * Fires background fetches and returns a promise that settles when all three
 * months have been attempted. When months are already cached this is a cheap
 * Map-lookup and resolves immediately.
 *
 * @param {number} unixSec - UTC Unix timestamp in seconds
 * @returns {Promise<void>}
 */
export function ensureMonthsForTime(unixSec) {
  const date  = new Date(unixSec * 1000);
  const year  = date.getUTCFullYear();
  const month = date.getUTCMonth() + 1;

  const toLoad = [];
  // Previous month (handles cross-year boundary)
  if (month === 1) toLoad.push([year - 1, 12]);
  else             toLoad.push([year, month - 1]);
  // Current month
  toLoad.push([year, month]);
  // Next month (handles cross-year boundary)
  if (month === 12) toLoad.push([year + 1, 1]);
  else              toLoad.push([year, month + 1]);

  return Promise.allSettled(toLoad.map(([y, m]) => loadMonth(y, m)));
}

/** Returns true if at least one month is loaded. */
export function isSolarWindDataLoaded() {
  return mergedView !== null;
}

/** Returns the year of the most recently cached month, or null. */
export function getSolarWindDataYear() {
  if (monthCache.size === 0) return null;
  const last = [...monthCache.values()].at(-1);
  return last ? last.year : null;
}

/**
 * Query solar wind parameters at a given UTC time.
 *
 * Returns the record whose epoch is the floor of unixSeconds (i.e. the most
 * recent full-hour record at or before the requested time).  Null entries are
 * linearly interpolated across short gaps.
 *
 * @param {number} unixSeconds - UTC Unix timestamp in seconds
 * @returns {{ vSw: number|null, nSw: number|null, By: number|null,
 *             Bz: number|null, Dst: number|null,
 *             G1: number|null, G2: number|null, interpolated: boolean } | null}
 *   Returns null when no data is loaded or the time is outside the loaded range.
 */
export function getSolarWindAtTime(unixSeconds) {
  if (!mergedView) return null;

  const { epochs } = mergedView;

  // Reject times clearly outside the loaded range (allow ±1 hour at boundaries).
  if (unixSeconds < epochs[0] - 3600 || unixSeconds > epochs[epochs.length - 1] + 3600) {
    return null;
  }

  const idx = floorIndex(epochs, unixSeconds);
  let interpolated = false;

  function get(arr) {
    if (arr[idx] !== null) return arr[idx];
    const r = resolveNull(arr, idx);
    if (r.interpolated) interpolated = true;
    return r.value;
  }

  return {
    vSw: get(mergedView.vSw),
    nSw: get(mergedView.nSw),
    By:  get(mergedView.By),
    Bz:  get(mergedView.Bz),
    Dst: get(mergedView.Dst),
    G1:  get(mergedView.G1),
    G2:  get(mergedView.G2),
    interpolated,
  };
}
