/**
 * solarWindData.js
 *
 * Loads and queries the historical OMNI2 hourly solar wind dataset.
 *
 * Data file: public/data/solarwind-YYYY.json
 * Generated by: scripts/convert-solarwind.js
 *
 * Missing hours in the source are stored as null.  getSolarWindAtTime() linearly
 * interpolates across gaps up to MAX_INTERP_GAP hours.  Longer gaps return null
 * for that parameter.  The `interpolated` flag in the return value is true whenever
 * any parameter was filled by interpolation, so the UI can indicate this.
 */

let data = null;

const MAX_INTERP_GAP = 6; // maximum gap length (hours) to interpolate across

/**
 * Load a year's solar wind data file.
 * Cached after the first load; calling again with a different year replaces the cache.
 *
 * @param {number} year - Calendar year (e.g. 2025)
 */
export async function loadSolarWindData(year = 2019) {
  const response = await fetch(`./data/solarwind-${year}.json`);
  if (!response.ok) throw new Error(`Failed to load solarwind-${year}.json: ${response.status}`);
  data = await response.json();
}

/** Returns true if a data file is currently loaded. */
export function isSolarWindDataLoaded() {
  return data !== null;
}

/** Returns the calendar year of the currently loaded data, or null. */
export function getSolarWindDataYear() {
  return data ? data.year : null;
}

// ---------------------------------------------------------------------------
// Binary search — floor index
// Returns the largest index i such that epochs[i] <= target.
// Clamps to 0 if target is before the first epoch.
// ---------------------------------------------------------------------------
function floorIndex(epochs, target) {
  let lo = 0, hi = epochs.length - 1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (epochs[mid] <= target) lo = mid;
    else hi = mid - 1;
  }
  return lo;
}

// ---------------------------------------------------------------------------
// Single-parameter interpolation across null gaps.
// Searches left and right from idx for the nearest non-null neighbours.
// Returns { value, interpolated }.
// ---------------------------------------------------------------------------
function resolveNull(arr, idx) {
  let lo = idx - 1;
  while (lo >= 0 && arr[lo] === null) lo--;

  let hi = idx + 1;
  while (hi < arr.length && arr[hi] === null) hi++;

  const hasLo = lo >= 0;
  const hasHi = hi < arr.length;

  if (!hasLo && !hasHi) return { value: null, interpolated: false };
  if (!hasLo)           return { value: arr[hi], interpolated: true };
  if (!hasHi)           return { value: arr[lo], interpolated: true };

  const gapSize = hi - lo - 1; // number of null hours between the two neighbours
  if (gapSize > MAX_INTERP_GAP) return { value: null, interpolated: false };

  const t = (idx - lo) / (hi - lo);
  return { value: arr[lo] + t * (arr[hi] - arr[lo]), interpolated: true };
}

/**
 * Query solar wind parameters at a given UTC time.
 *
 * Returns the record whose epoch is the floor of unixSeconds (i.e. the most
 * recent full-hour record at or before the requested time).  Null entries are
 * linearly interpolated across short gaps.
 *
 * @param {number} unixSeconds - UTC Unix timestamp in seconds
 * @returns {{ vSw: number|null, nSw: number|null, By: number|null,
 *             Bz: number|null, Dst: number|null,
 *             G1: number|null, G2: number|null, interpolated: boolean } | null}
 *   Returns null when no data is loaded or the time is outside the loaded year.
 *   G1 and G2 are null for years without Qin-Denton data (> 2019).
 */
export function getSolarWindAtTime(unixSeconds) {
  if (!data) return null;

  const { epochs } = data;

  // Reject times clearly outside the loaded year (allow ±1 hour at boundaries)
  if (unixSeconds < epochs[0] - 3600 || unixSeconds > epochs[epochs.length - 1] + 3600) {
    return null;
  }

  const idx = floorIndex(epochs, unixSeconds);
  let interpolated = false;

  function get(arr) {
    if (arr[idx] !== null) return arr[idx];
    const r = resolveNull(arr, idx);
    if (r.interpolated) interpolated = true;
    return r.value;
  }

  return {
    vSw: get(data.vSw),
    nSw: get(data.nSw),
    By:  get(data.By),
    Bz:  get(data.Bz),
    Dst: get(data.Dst),
    G1:  data.G1 ? get(data.G1) : null,
    G2:  data.G2 ? get(data.G2) : null,
    interpolated,
  };
}
